<eclipse>
<message date="1/1/0" time="0.00000000000000">
 CHECKING FOR LICENSES                                                   
</message>
<message date="1/1/0" time="0.00000000000000">
 CHECKING FOR LICENSES                                                   
</message>
<message date="1/1/1983" time="0.00000000000000">
 CHECKING FOR LICENSES                                                   
</message>
<message date="1/1/1983" time="0.00000000000000">
 THE MEMORY REQUIRED TO PROCESS THE GRID SECTION IS                      
      31696 BYTES                                                        
</message>
<warning date="1/1/1983" time="0.00000000000000">
 PLEASE RE-CHECK TOPS DATA SPECIFIED.  THE FIRST                         
 AND SECOND LAYERS HAVE SAME TOPS VALUE                                  
</warning>
<message date="1/1/1983" time="0.00000000000000">
 NEITHER OLDTRAN,OLDTRANR NOR NEWTRAN SPECIFIED                          
 BLOCK CENTRE TRANSMISSIBILITIES TO BE CALCULATED                        
 USING  OLDTRAN                                                          
</message>
<comment date="1/1/1983" time="0.00000000000000">
 NO NON-NEIGHBOUR CONNECTIONS FOUND                                      
</comment>
<message date="1/1/1983" time="0.00000000000000">
 NUMBER OF ACTIVE CELLS IS 40                                            
</message>
<message date="1/1/1983" time="0.00000000000000">
 THE MEMORY REQUIRED TO PROCESS THE SOLUTION SECTION IS                  
     336756 BYTES                                                        
</message>
<message date="1/1/1983" time="0.00000000000000">
    58543 CHARACTER VARIABLES USED                                       
</message>
<warning date="1/1/1983" time="0.00000000000000">
 THE MASS DENSITY OF THE ROCK HAS BEEN                                   
 SPECIFIED IN SURFROCK TABLE NUMBER    1                                 
 THIS DENSITY WILL BE IGNORED AS THE POLYMER                             
 OPTION IS ACTIVE                                                        
</warning>
<warning date="1/1/1983" time="0.00000000000000">
 THE MASS DENSITY OF THE ROCK HAS BEEN                                   
 SPECIFIED IN SURFROCK TABLE NUMBER    2                                 
 THIS DENSITY WILL BE IGNORED AS THE POLYMER                             
 OPTION IS ACTIVE                                                        
</warning>
<message date="1/1/1983" time="0.00000000000000">
 PLYROCK TABLE:   2                                                      
 CRITICAL WATER SATURATION IS  0.000                                     
 DEAD PORE VOLUME SATURATION IS 0.1600                                   
</message>
</eclipse>
