<eclipse>
<message date="1/1/1988" time="0.00000000000000">
 CHECKING FOR LICENSES                                                   
</message>
<message date="1/1/1988" time="0.00000000000000">
 THE MEMORY REQUIRED TO PROCESS THE GRID SECTION IS                      
      84468 BYTES                                                        
</message>
<message date="1/1/1988" time="0.00000000000000">
 12 NON-NEIGHBOUR CONNECTIONS PRESENT                                    
</message>
<message date="1/1/1988" time="0.00000000000000">
 NUMBER OF ACTIVE CELLS IS 200                                           
</message>
<message date="1/1/1988" time="0.00000000000000">
 THE MEMORY REQUIRED TO PROCESS THE SOLUTION SECTION IS                  
     519340 BYTES                                                        
</message>
<message date="1/1/1988" time="0.00000000000000">
    58535 CHARACTER VARIABLES USED                                       
</message>
<warning date="1/1/1988" time="0.00000000000000">
 THE BOTTOM HOLE PRESSURE LIMIT FOR WELL I                               
 HAS BEEN DEFAULTED. THE DEFAULT VALUE IS  100000.   PSIA                
</warning>
<message date="1/1/1988" time="0.00000000000000">
 DRSDT KEYWORD HAS NOT BEEN ENTERED, SO THE                              
 MAXIMUM GAS RE-SOLUTION RATE IS DEFAULTED TO INFINITY.                  
</message>
<message date="1/1/1988" time="0.00000000000000">
 RESTART FILE WRITTEN   REPORT     0                                     
</message>
<message date="19/7/1988" time="200.00000000000000">
 RESTART FILE WRITTEN   REPORT     1                                     
 RESTART INCLUDES FLUIDS IN PLACE                                        
</message>
<message date="27/10/1988" time="300.00000000000000">
 RESTART FILE WRITTEN   REPORT     2                                     
 RESTART INCLUDES FLUIDS IN PLACE                                        
</message>
<message date="4/2/1989" time="400.00000000000000">
 RESTART FILE WRITTEN   REPORT     3                                     
 RESTART INCLUDES FLUIDS IN PLACE                                        
</message>
<message date="15/5/1989" time="500.00000000000000">
 RESTART FILE WRITTEN   REPORT     4                                     
 RESTART INCLUDES FLUIDS IN PLACE                                        
</message>
<message date="9/2/1992" time="1500.00000000000000">
 RESTART FILE WRITTEN   REPORT     5                                     
 RESTART INCLUDES FLUIDS IN PLACE                                        
</message>
<message date="15/5/1992" time="1596.98746133029204">
 ******************************************                              
 * WELL P        HAS CHANGED TO           *                              
 * CONTROL BY BOTTOM HOLE PRESSURE        *                              
 * FROM TIME   1596.99   DAYS  .          *                              
 ******************************************                              
</message>
<message date="8/7/1992" time="1650.00000000000000">
 RESTART FILE WRITTEN   REPORT     6                                     
 RESTART INCLUDES FLUIDS IN PLACE                                        
</message>
<message date="23/6/1993" time="2000.00000000000000">
 RESTART FILE WRITTEN   REPORT     7                                     
 RESTART INCLUDES FLUIDS IN PLACE                                        
</message>
<message date="19/3/1996" time="3000.00000000000000">
 RESTART FILE WRITTEN   REPORT     8                                     
 RESTART INCLUDES FLUIDS IN PLACE                                        
</message>
</eclipse>
