<eclipse>
<message date="1/1/1990" time="0.00000000000000">
 CHECKING FOR LICENSES                                                   
</message>
<message date="1/1/1990" time="0.00000000000000">
 THE MEMORY REQUIRED TO PROCESS THE GRID SECTION IS                      
     422609 KBYTES                                                       
</message>
<message date="1/1/1990" time="0.00000000000000">
 CHECKING FOR LICENSES                                                   
</message>
<message date="1/1/1990" time="0.00000000000000">
 UNSPECIFIED TOPS VALUES OBTAINED BY ADDING DZ                           
 TO TOPS VALUE FOR LAYER ABOVE                                           
</message>
<message date="1/1/1990" time="0.00000000000000">
 NEITHER OLDTRAN,OLDTRANR NOR NEWTRAN SPECIFIED                          
 BLOCK CENTRE TRANSMISSIBILITIES TO BE CALCULATED                        
 USING  OLDTRAN                                                          
</message>
<message date="1/1/1990" time="0.00000000000000">
 NUMBER OF ACTIVE CELLS IS 1125000                                       
</message>
<error date="1/1/1990" time="0.00000000000000">
 UNABLE TO ALLOCATE MEMORY FOR ARRAY A                                   
 OF TYPE DOUBLE  , LENGTH         70875001,                              
 AND REQUIRING   553710 KBYTES.                                          
 THE SYSTEM ERROR RETURNED WAS       41                                  
          852 MBYTES PREVIOUSLY ALLOCATED                                
 THIS IS AN OUT-OF-MEMORY CONDITION.                                     
</error>
</eclipse>
