<eclipse>
<message date="1/1/1990" time="0.00000000000000">
 CHECKING FOR LICENSES                                                   
</message>
<message date="1/1/1990" time="0.00000000000000">
 THE MEMORY REQUIRED TO PROCESS THE GRID SECTION IS                      
     952976 BYTES                                                        
</message>
<message date="1/1/1990" time="0.00000000000000">
 CHECKING FOR LICENSES                                                   
</message>
<message date="1/1/1990" time="0.00000000000000">
  THE MULTNUM ARRAY WILL BE USED WITH THE MULTREGP                       
  KEYWORD                                                                
</message>
<message date="1/1/1990" time="0.00000000000000">
 MULTREGP WILL REFER TO FLUX REGIONS                                     
</message>
<message date="1/1/1990" time="0.00000000000000">
     83   PINCH-OUT CONNECTIONS GENERATED                                
</message>
<message date="1/1/1990" time="0.00000000000000">
 PRE-PROCESSING HAS FOUND       83 NON-NEIGHBOUR CONNECTIONS             
 WHICH EITHER JOIN ADJACENT CELLS OR CAN BE TREATED AS A                 
 NORMAL CONNECTION. THE TRANSMISSIBILITY HAS BEEN ADDED TO               
 THE APPROPRIATE CELL TRANSMISSIBILITY AND THE                           
 NON-NEIGHBOUR CONNECTION REMOVED FROM THE SIMULATION                    
</message>
<message date="1/1/1990" time="0.00000000000000">
 127 NON-NEIGHBOUR CONNECTIONS PRESENT                                   
</message>
<message date="1/1/1990" time="0.00000000000000">
 NUMBER OF ACTIVE CELLS IS 1639                                          
</message>
<message date="1/1/1990" time="0.00000000000000">
 THE MEMORY REQUIRED TO PROCESS THE SOLUTION SECTION IS                  
       4167 KBYTES                                                       
</message>
<message date="1/1/1990" time="0.00000000000000">
    58691 CHARACTER VARIABLES USED                                       
</message>
<warning date="1/1/1990" time="0.00000000000000">
 KEYWORD TEMPTVD SHOULD ONLY BE USED IF                                  
 THE TEMPERATURE OPTIONS HAS BEEN REQUESTED                              
 USING THE TEMP KEYWORD IN RUNSPEC                                       
</warning>
<warning date="1/1/1990" time="0.00000000000000">
 POST-PROCESSORS MAY HAVE TROUBLE READING RESULTS FOR TRACERS            
 WHOSE NAME BEGIN WITH EITHER F OR S                                     
</warning>
<message date="1/1/1990" time="0.00000000000000">
 SAVE FILE HAS BEEN WRITTEN.                                             
</message>
<warning date="1/1/1990" time="0.00000000000000">
 A CELL HAS BEEN DETECTED IN AQUANCON                                    
 THAT HAS AN ACTIVE CELL ON ITS                                          
 AQUIFER FACING SIDE. THIS CELL WILL                                     
 NOT BE CONNECTED. A FULL LIST OF                                        
 CELLS CAN BE OBTAINED USING                                             
 OPTIONS(99). IN ORDER TO CONNECT                                        
 THESE CELLS SET ITEM 11 OF AQUANCON.                                    
</warning>
<message date="1/1/1990" time="0.00000000000000">
 AQUIFER      1 HAS    212 CONNECTIONS IN THE                            
 GLOBAL GRID                                                             
</message>
<message date="1/1/1990" time="0.00000000000000">
 AQUIFER      2 HAS     72 CONNECTIONS IN THE                            
 GLOBAL GRID                                                             
</message>
<message date="1/1/1990" time="0.00000000000000">
 AQUIFER      3 HAS     66 CONNECTIONS IN THE                            
 GLOBAL GRID                                                             
</message>
<comment date="1/1/1990" time="0.00000000000000">
 THE MINIMUM VALUE FOR NCAMAX IN THE AQUDIMS KEYWORD                     
 IN RUNSPEC IS       212                                                 
</comment>
<warning date="1/1/1990" time="0.00000000000000">
 WELL I1       CONNECTS WITH A DEAD BLOCK                                
 (  16   2   4). THIS CONNECTION WILL BE IGNORED.                        
</warning>
<warning date="1/1/1990" time="0.00000000000000">
 WELL I1       CONNECTS WITH A DEAD BLOCK                                
 (  16   2   6). THIS CONNECTION WILL BE IGNORED.                        
</warning>
<warning date="1/1/1990" time="0.00000000000000">
 WELL I3       CONNECTS WITH A DEAD BLOCK                                
 (  19  12   4). THIS CONNECTION WILL BE IGNORED.                        
</warning>
<warning date="1/1/1990" time="0.00000000000000">
 WELL I3       CONNECTS WITH A DEAD BLOCK                                
 (  19  12   6). THIS CONNECTION WILL BE IGNORED.                        
</warning>
<warning date="1/1/1990" time="0.00000000000000">
 WELL I5       CONNECTS WITH A DEAD BLOCK                                
 (   5  15   6). THIS CONNECTION WILL BE IGNORED.                        
</warning>
<warning date="1/1/1990" time="0.00000000000000">
 WELL I7       CONNECTS WITH A DEAD BLOCK                                
 (   2   5   6). THIS CONNECTION WILL BE IGNORED.                        
</warning>
<warning date="1/1/1990" time="0.00000000000000">
 WELL I2       CONNECTS WITH A DEAD BLOCK                                
 (  20   8   4). THIS CONNECTION WILL BE IGNORED.                        
</warning>
<warning date="1/1/1990" time="0.00000000000000">
 WELL I2       CONNECTS WITH A DEAD BLOCK                                
 (  20   8   6). THIS CONNECTION WILL BE IGNORED.                        
</warning>
<warning date="1/1/1990" time="0.00000000000000">
 WELL I4       CONNECTS WITH A DEAD BLOCK                                
 (  17  14   6). THIS CONNECTION WILL BE IGNORED.                        
</warning>
<warning date="1/1/1990" time="0.00000000000000">
 WELL I6       CONNECTS WITH A DEAD BLOCK                                
 (   1  12   6). THIS CONNECTION WILL BE IGNORED.                        
</warning>
<warning date="1/1/1990" time="0.00000000000000">
 WELL I8       CONNECTS WITH A DEAD BLOCK                                
 (   8   1   4). THIS CONNECTION WILL BE IGNORED.                        
</warning>
<warning date="1/1/1990" time="0.00000000000000">
 WELL I8       CONNECTS WITH A DEAD BLOCK                                
 (   8   1   6). THIS CONNECTION WILL BE IGNORED.                        
</warning>
<warning date="1/1/1990" time="0.00000000000000">
 WELL U1       CONNECTS WITH A DEAD BLOCK                                
 (  14   6   4). THIS CONNECTION WILL BE IGNORED.                        
</warning>
<warning date="1/1/1990" time="0.00000000000000">
 WELL U2       CONNECTS WITH A DEAD BLOCK                                
 (  17   8   4). THIS CONNECTION WILL BE IGNORED.                        
</warning>
<warning date="1/1/1990" time="0.00000000000000">
 WELL LU1      CONNECTS WITH A DEAD BLOCK                                
 (  14   8   4). THIS CONNECTION WILL BE IGNORED.                        
</warning>
<warning date="1/1/1990" time="0.00000000000000">
 WELL I1       IS AN INJECTOR. THE LIFT DATA                             
 SPECIFIED IN KEYWORD WLIFT WILL NOT APPLY TO IT.                        
</warning>
<warning date="1/1/1990" time="0.00000000000000">
 WELL I3       IS AN INJECTOR. THE LIFT DATA                             
 SPECIFIED IN KEYWORD WLIFT WILL NOT APPLY TO IT.                        
</warning>
<warning date="1/1/1990" time="0.00000000000000">
 WELL I5       IS AN INJECTOR. THE LIFT DATA                             
 SPECIFIED IN KEYWORD WLIFT WILL NOT APPLY TO IT.                        
</warning>
<warning date="1/1/1990" time="0.00000000000000">
 WELL I7       IS AN INJECTOR. THE LIFT DATA                             
 SPECIFIED IN KEYWORD WLIFT WILL NOT APPLY TO IT.                        
</warning>
<warning date="1/1/1990" time="0.00000000000000">
 WELL GI       IS AN INJECTOR. THE LIFT DATA                             
 SPECIFIED IN KEYWORD WLIFT WILL NOT APPLY TO IT.                        
</warning>
<warning date="1/1/1990" time="0.00000000000000">
 WELL I2       IS AN INJECTOR. THE LIFT DATA                             
 SPECIFIED IN KEYWORD WLIFT WILL NOT APPLY TO IT.                        
</warning>
<warning date="1/1/1990" time="0.00000000000000">
 WELL I4       IS AN INJECTOR. THE LIFT DATA                             
 SPECIFIED IN KEYWORD WLIFT WILL NOT APPLY TO IT.                        
</warning>
<warning date="1/1/1990" time="0.00000000000000">
 WELL I6       IS AN INJECTOR. THE LIFT DATA                             
 SPECIFIED IN KEYWORD WLIFT WILL NOT APPLY TO IT.                        
</warning>
<warning date="1/1/1990" time="0.00000000000000">
 WELL I8       IS AN INJECTOR. THE LIFT DATA                             
 SPECIFIED IN KEYWORD WLIFT WILL NOT APPLY TO IT.                        
</warning>
<message date="1/1/1990" time="0.00000000000000">
 THE TOP-UP PHASE IS SET TO WATER AS                                     
 GROUP FIELD    HAS A TARGET OR LIMIT RESERVOIR                          
 VOLUME RATE OR VOIDAGE REPLACEMENT FRACTION                             
 FOR WATER INJECTION CONTROL                                             
</message>
<message date="1/1/1990" time="0.00000000000000">
 RESTART FILE WRITTEN   REPORT     0                                     
 RESTART INCLUDES FLUIDS IN PLACE                                        
</message>
<message date="1/1/1990" time="0.00000000000000">
 WRITING FLUX BOUNDARY CONDITIONS TO FLUX FILE                           
</message>
<message date="1/1/1990" time="0.00000000000000">
 ***********************************************                         
 * DRILLING RIG NUMBER 100 OCCUPIED WITH       *                         
 * WELL LU1      UNTIL TIME      60.00  DAYS   *                         
 ***********************************************                         
</message>
<message date="1/1/1990" time="0.00000000000000">
 **********************************************************              
 * WELL LU1      IS OPENED AT TIME      0.00  DAYS        *              
 * ( WITH ZERO EFFICIENCY FACTOR UNTIL     60.00  DAYS  ) *              
 **********************************************************              
</message>
<message date="1/1/1990" time="0.00000000000000">
 ******************************************                              
 * WELL LU1      HAS CHANGED TO           *                              
 * CONTROL BY OIL RATE                    *                              
 * FROM TIME      0.00   DAYS  .          *                              
 ******************************************                              
</message>
<message date="1/1/1990" time="0.00000000000000">
 **********************************************                          
 * WELL GI       HAS CHANGED TO GROUP CONTROL *                          
 * FROM TIME      0.00   DAYS  .              *                          
 **********************************************                          
</message>
<message date="1/1/1990" time="0.00000000000000">
 ******************************************                              
 * GROUP ONE      IS NO LONGER UNDER      *                              
 * WATER  INJECTION  RES VOL RATE CONTROL *                              
 * FROM TIME      0.00   DAYS  .          *                              
 ******************************************                              
</message>
<message date="1/1/1990" time="0.00000000000000">
 ******************************************                              
 * GROUP TWO      IS NO LONGER UNDER      *                              
 * WATER  INJECTION  RES VOL RATE CONTROL *                              
 * FROM TIME      0.00   DAYS  .          *                              
 ******************************************                              
</message>
<message date="20/2/1990" time="50.36551817794040">
 ***********************************************                         
 * DRILLING RIG NUMBER 100 OCCUPIED WITH       *                         
 * WELL LU2      UNTIL TIME     120.00  DAYS   *                         
 ***********************************************                         
</message>
<message date="20/2/1990" time="50.36551817794040">
 **********************************************************              
 * WELL LU2      IS OPENED AT TIME     50.37  DAYS        *              
 * ( WITH ZERO EFFICIENCY FACTOR UNTIL    120.00  DAYS  ) *              
 **********************************************************              
</message>
<message date="20/2/1990" time="50.36551817794040">
 ******************************************                              
 * WELL LU2      HAS CHANGED TO           *                              
 * CONTROL BY OIL RATE                    *                              
 * FROM TIME     50.37   DAYS  .          *                              
 ******************************************                              
</message>
<message date="20/2/1990" time="50.36551817794040">
 **********************************                                      
 * GROUP FIELD    CANNOT MEET ITS *                                      
 * WATER  INJECTION  TARGET       *                                      
 * AFTER TIME     50.37   DAYS  . *                                      
 **********************************                                      
</message>
<message date="23/4/1990" time="112.05376952269060">
 ***********************************************                         
 * DRILLING RIG NUMBER 100 OCCUPIED WITH       *                         
 * WELL U3       UNTIL TIME     180.00  DAYS   *                         
 ***********************************************                         
</message>
<message date="23/4/1990" time="112.05376952269060">
 **********************************************************              
 * WELL U3       IS OPENED AT TIME    112.05  DAYS        *              
 * ( WITH ZERO EFFICIENCY FACTOR UNTIL    180.00  DAYS  ) *              
 **********************************************************              
</message>
<message date="23/4/1990" time="112.05376952269060">
 ******************************************                              
 * WELL U3       HAS CHANGED TO           *                              
 * CONTROL BY OIL RATE                    *                              
 * FROM TIME    112.05   DAYS  .          *                              
 ******************************************                              
</message>
<message date="24/5/1990" time="143.83944092066449">
 ***********************************************                         
 * DRILLING RIG NUMBER 100 OCCUPIED WITH       *                         
 * WELL U5       UNTIL TIME     240.00  DAYS   *                         
 ***********************************************                         
</message>
<message date="24/5/1990" time="143.83944092066449">
 **********************************************************              
 * WELL U5       IS OPENED AT TIME    143.84  DAYS        *              
 * ( WITH ZERO EFFICIENCY FACTOR UNTIL    240.00  DAYS  ) *              
 **********************************************************              
</message>
<message date="24/5/1990" time="143.83944092066449">
 ******************************************                              
 * WELL LU1      HAS CHANGED TO           *                              
 * CONTROL BY TUBING HEAD PRESSURE        *                              
 * FROM TIME    143.84   DAYS  .          *                              
 ******************************************                              
</message>
<message date="24/5/1990" time="143.83944092066449">
 ******************************************                              
 * WELL U5       HAS CHANGED TO           *                              
 * CONTROL BY OIL RATE                    *                              
 * FROM TIME    143.84   DAYS  .          *                              
 ******************************************                              
</message>
<message date="8/7/1990" time="188.47691445823671">
 ***********************************************                         
 * DRILLING RIG NUMBER 100 OCCUPIED WITH       *                         
 * WELL I1       UNTIL TIME     300.00  DAYS   *                         
 ***********************************************                         
</message>
<message date="8/7/1990" time="188.47691445823671">
 **********************************************************              
 * WELL I1       IS OPENED AT TIME    188.48  DAYS        *              
 * ( WITH ZERO EFFICIENCY FACTOR UNTIL    300.00  DAYS  ) *              
 **********************************************************              
</message>
<message date="8/7/1990" time="188.47691445823671">
 ******************************************                              
 * WELL LU2      HAS CHANGED TO           *                              
 * CONTROL BY TUBING HEAD PRESSURE        *                              
 * FROM TIME    188.48   DAYS  .          *                              
 ******************************************                              
</message>
<message date="8/7/1990" time="188.47691445823671">
 ******************************************                              
 * WELL I1       HAS CHANGED TO           *                              
 * CONTROL BY RESERVOIR FLUID VOLUME RATE *                              
 * FROM TIME    188.48   DAYS  .          *                              
 ******************************************                              
</message>
<message date="4/9/1990" time="246.35407621440532">
 ***********************************************                         
 * DRILLING RIG NUMBER 100 OCCUPIED WITH       *                         
 * WELL I3       UNTIL TIME     360.00  DAYS   *                         
 ***********************************************                         
</message>
<message date="4/9/1990" time="246.35407621440532">
 **********************************************************              
 * WELL I3       IS OPENED AT TIME    246.35  DAYS        *              
 * ( WITH ZERO EFFICIENCY FACTOR UNTIL    360.00  DAYS  ) *              
 **********************************************************              
</message>
<message date="4/9/1990" time="246.35407621440532">
 ******************************************                              
 * WELL I3       HAS CHANGED TO           *                              
 * CONTROL BY RESERVOIR FLUID VOLUME RATE *                              
 * FROM TIME    246.35   DAYS  .          *                              
 ******************************************                              
</message>
<message date="2/11/1990" time="305.67703810720263">
 ***********************************************                         
 * DRILLING RIG NUMBER 100 OCCUPIED WITH       *                         
 * WELL I5       UNTIL TIME     420.00  DAYS   *                         
 ***********************************************                         
</message>
<message date="2/11/1990" time="305.67703810720263">
 **********************************************************              
 * WELL I5       IS OPENED AT TIME    305.68  DAYS        *              
 * ( WITH ZERO EFFICIENCY FACTOR UNTIL    420.00  DAYS  ) *              
 **********************************************************              
</message>
<message date="2/11/1990" time="305.67703810720263">
 ******************************************                              
 * WELL U3       HAS CHANGED TO           *                              
 * CONTROL BY GAS RATE                    *                              
 * FROM TIME    305.68   DAYS  .          *                              
 ******************************************                              
</message>
<message date="2/11/1990" time="305.67703810720263">
 ******************************************                              
 * WELL I5       HAS CHANGED TO           *                              
 * CONTROL BY RESERVOIR FLUID VOLUME RATE *                              
 * FROM TIME    305.68   DAYS  .          *                              
 ******************************************                              
</message>
<message date="1/1/1991" time="365.00000000000000">
 RESTART FILE WRITTEN   REPORT     1                                     
 RESTART INCLUDES FLUIDS IN PLACE                                        
</message>
<message date="1/1/1991" time="365.00000000000000">
 ***********************************************                         
 * DRILLING RIG NUMBER 100 OCCUPIED WITH       *                         
 * WELL I7       UNTIL TIME     480.00  DAYS   *                         
 ***********************************************                         
</message>
<message date="1/1/1991" time="365.00000000000000">
 **********************************************************              
 * WELL I7       IS OPENED AT TIME    365.00  DAYS        *              
 * ( WITH ZERO EFFICIENCY FACTOR UNTIL    480.00  DAYS  ) *              
 **********************************************************              
</message>
<message date="1/1/1991" time="365.00000000000000">
 **********************************************                          
 * WELL LU2      HAS CHANGED TO GROUP CONTROL *                          
 * FROM TIME    365.00   DAYS  .              *                          
 **********************************************                          
</message>
<message date="1/1/1991" time="365.00000000000000">
 ******************************************                              
 * WELL I7       HAS CHANGED TO           *                              
 * CONTROL BY RESERVOIR FLUID VOLUME RATE *                              
 * FROM TIME    365.00   DAYS  .          *                              
 ******************************************                              
</message>
<message date="4/4/1991" time="458.63237355991288">
 ***********************************************                         
 * DRILLING RIG NUMBER 100 OCCUPIED WITH       *                         
 * WELL U1       UNTIL TIME     540.00  DAYS   *                         
 ***********************************************                         
</message>
<message date="4/4/1991" time="458.63237355991288">
 **********************************************************              
 * WELL U1       IS OPENED AT TIME    458.63  DAYS        *              
 * ( WITH ZERO EFFICIENCY FACTOR UNTIL    540.00  DAYS  ) *              
 **********************************************************              
</message>
<message date="4/4/1991" time="458.63237355991288">
 ***********************************************                         
 * DRILLING RIG NUMBER 100 OCCUPIED WITH       *                         
 * WELL U2       UNTIL TIME     600.00  DAYS   *                         
 ***********************************************                         
</message>
<message date="4/4/1991" time="458.63237355991288">
 **********************************************************              
 * WELL U2       IS OPENED AT TIME    458.63  DAYS        *              
 * ( WITH ZERO EFFICIENCY FACTOR UNTIL    600.00  DAYS  ) *              
 **********************************************************              
</message>
<message date="4/4/1991" time="458.63237355991288">
 ******************************************                              
 * WELL U5       HAS CHANGED TO           *                              
 * CONTROL BY GAS RATE                    *                              
 * FROM TIME    458.63   DAYS  .          *                              
 ******************************************                              
</message>
<message date="4/4/1991" time="458.63237355991288">
 **********************************************                          
 * WELL I1       HAS CHANGED TO GROUP CONTROL *                          
 * FROM TIME    458.63   DAYS  .              *                          
 **********************************************                          
</message>
<message date="4/4/1991" time="458.63237355991288">
 **********************************************                          
 * WELL I3       HAS CHANGED TO GROUP CONTROL *                          
 * FROM TIME    458.63   DAYS  .              *                          
 **********************************************                          
</message>
<message date="4/4/1991" time="458.63237355991288">
 **********************************************                          
 * WELL I5       HAS CHANGED TO GROUP CONTROL *                          
 * FROM TIME    458.63   DAYS  .              *                          
 **********************************************                          
</message>
<message date="4/4/1991" time="458.63237355991288">
 **********************************************                          
 * WELL I7       HAS CHANGED TO GROUP CONTROL *                          
 * FROM TIME    458.63   DAYS  .              *                          
 **********************************************                          
</message>
<message date="4/4/1991" time="458.63237355991288">
 ******************************************                              
 * WELL U1       HAS CHANGED TO           *                              
 * CONTROL BY OIL RATE                    *                              
 * FROM TIME    458.63   DAYS  .          *                              
 ******************************************                              
</message>
<message date="4/4/1991" time="458.63237355991288">
 ******************************************                              
 * WELL U2       HAS CHANGED TO           *                              
 * CONTROL BY OIL RATE                    *                              
 * FROM TIME    458.63   DAYS  .          *                              
 ******************************************                              
</message>
<message date="4/4/1991" time="458.63237355991288">
 **********************************                                      
 * GROUP FIELD    CAN MEET ITS    *                                      
 * WATER  INJECTION  TARGET       *                                      
 * AFTER TIME    458.63   DAYS  . *                                      
 **********************************                                      
</message>
<message date="15/8/1991" time="591.93954877032320">
 ***********************************************                         
 * DRILLING RIG NUMBER 100 OCCUPIED WITH       *                         
 * WELL U4       UNTIL TIME     660.00  DAYS   *                         
 ***********************************************                         
</message>
<message date="15/8/1991" time="591.93954877032320">
 **********************************************************              
 * WELL U4       IS OPENED AT TIME    591.94  DAYS        *              
 * ( WITH ZERO EFFICIENCY FACTOR UNTIL    660.00  DAYS  ) *              
 **********************************************************              
</message>
<message date="15/8/1991" time="591.93954877032320">
 ***********************************************                         
 * DRILLING RIG NUMBER 100 OCCUPIED WITH       *                         
 * WELL L1       UNTIL TIME     720.00  DAYS   *                         
 ***********************************************                         
</message>
<message date="15/8/1991" time="591.93954877032320">
 **********************************************************              
 * WELL L1       IS OPENED AT TIME    591.94  DAYS        *              
 * ( WITH ZERO EFFICIENCY FACTOR UNTIL    720.00  DAYS  ) *              
 **********************************************************              
</message>
<message date="15/8/1991" time="591.93954877032320">
 ***********************************************                         
 * DRILLING RIG NUMBER 100 OCCUPIED WITH       *                         
 * WELL L2       UNTIL TIME     780.00  DAYS   *                         
 ***********************************************                         
</message>
<message date="15/8/1991" time="591.93954877032320">
 **********************************************************              
 * WELL L2       IS OPENED AT TIME    591.94  DAYS        *              
 * ( WITH ZERO EFFICIENCY FACTOR UNTIL    780.00  DAYS  ) *              
 **********************************************************              
</message>
<message date="15/8/1991" time="591.93954877032320">
 **********************************************                          
 * WELL LU1      HAS CHANGED TO GROUP CONTROL *                          
 * FROM TIME    591.94   DAYS  .              *                          
 **********************************************                          
</message>
<message date="15/8/1991" time="591.93954877032320">
 ******************************************                              
 * WELL U4       HAS CHANGED TO           *                              
 * CONTROL BY OIL RATE                    *                              
 * FROM TIME    591.94   DAYS  .          *                              
 ******************************************                              
</message>
<message date="15/8/1991" time="591.93954877032320">
 ******************************************                              
 * WELL L1       HAS CHANGED TO           *                              
 * CONTROL BY OIL RATE                    *                              
 * FROM TIME    591.94   DAYS  .          *                              
 ******************************************                              
</message>
<message date="15/8/1991" time="591.93954877032320">
 ******************************************                              
 * WELL L2       HAS CHANGED TO           *                              
 * CONTROL BY OIL RATE                    *                              
 * FROM TIME    591.94   DAYS  .          *                              
 ******************************************                              
</message>
<message date="15/8/1991" time="591.93954877032320">
 ******************************************                              
 * GROUP FIELD    HAS CHANGED TO          *                              
 * WATER  INJECTION  SURFACE RATE CONTROL *                              
 * FROM TIME    591.94   DAYS  .          *                              
 ******************************************                              
</message>
<message date="1/1/1992" time="730.00000000000000">
 RESTART FILE WRITTEN   REPORT     2                                     
 RESTART INCLUDES FLUIDS IN PLACE                                        
</message>
<message date="1/1/1992" time="730.00000000000000">
 ***********************************************                         
 * DRILLING RIG NUMBER 100 OCCUPIED WITH       *                         
 * WELL L3       UNTIL TIME     840.00  DAYS   *                         
 ***********************************************                         
</message>
<message date="1/1/1992" time="730.00000000000000">
 **********************************************************              
 * WELL L3       IS OPENED AT TIME    730.00  DAYS        *              
 * ( WITH ZERO EFFICIENCY FACTOR UNTIL    840.00  DAYS  ) *              
 **********************************************************              
</message>
<message date="1/1/1992" time="730.00000000000000">
 **********************************************                          
 * WELL U5       HAS CHANGED TO GROUP CONTROL *                          
 * FROM TIME    730.00   DAYS  .              *                          
 **********************************************                          
</message>
<message date="1/1/1992" time="730.00000000000000">
 ******************************************                              
 * WELL U4       HAS CHANGED TO           *                              
 * CONTROL BY GAS RATE                    *                              
 * FROM TIME    730.00   DAYS  .          *                              
 ******************************************                              
</message>
<message date="1/1/1992" time="730.00000000000000">
 ******************************************                              
 * WELL L3       HAS CHANGED TO           *                              
 * CONTROL BY OIL RATE                    *                              
 * FROM TIME    730.00   DAYS  .          *                              
 ******************************************                              
</message>
<message date="16/4/1992" time="836.10353343641486">
 ***********************************************                         
 * DRILLING RIG NUMBER 100 OCCUPIED WITH       *                         
 * WELL I2       UNTIL TIME     900.00  DAYS   *                         
 ***********************************************                         
</message>
<message date="16/4/1992" time="836.10353343641486">
 **********************************************************              
 * WELL I2       IS OPENED AT TIME    836.10  DAYS        *              
 * ( WITH ZERO EFFICIENCY FACTOR UNTIL    900.00  DAYS  ) *              
 **********************************************************              
</message>
<message date="16/4/1992" time="836.10353343641486">
 ***********************************************                         
 * DRILLING RIG NUMBER 100 OCCUPIED WITH       *                         
 * WELL I4       UNTIL TIME     960.00  DAYS   *                         
 ***********************************************                         
</message>
<message date="16/4/1992" time="836.10353343641486">
 **********************************************************              
 * WELL I4       IS OPENED AT TIME    836.10  DAYS        *              
 * ( WITH ZERO EFFICIENCY FACTOR UNTIL    960.00  DAYS  ) *              
 **********************************************************              
</message>
<message date="16/4/1992" time="836.10353343641486">
 ******************************************                              
 * WELL U2       HAS CHANGED TO           *                              
 * CONTROL BY TUBING HEAD PRESSURE        *                              
 * FROM TIME    836.10   DAYS  .          *                              
 ******************************************                              
</message>
<message date="16/4/1992" time="836.10353343641486">
 **********************************************                          
 * WELL I2       HAS CHANGED TO GROUP CONTROL *                          
 * FROM TIME    836.10   DAYS  .              *                          
 **********************************************                          
</message>
<message date="16/4/1992" time="836.10353343641486">
 **********************************************                          
 * WELL I4       HAS CHANGED TO GROUP CONTROL *                          
 * FROM TIME    836.10   DAYS  .              *                          
 **********************************************                          
</message>
<message date="20/7/1992" time="931.90720231215448">
 ***********************************************                         
 * DRILLING RIG NUMBER 100 OCCUPIED WITH       *                         
 * WELL I6       UNTIL TIME    1020.00  DAYS   *                         
 ***********************************************                         
</message>
<message date="20/7/1992" time="931.90720231215448">
 **********************************************************              
 * WELL I6       IS OPENED AT TIME    931.91  DAYS        *              
 * ( WITH ZERO EFFICIENCY FACTOR UNTIL   1020.00  DAYS  ) *              
 **********************************************************              
</message>
<message date="20/7/1992" time="931.90720231215448">
 ******************************************                              
 * WELL U5       HAS CHANGED TO           *                              
 * CONTROL BY GAS RATE                    *                              
 * FROM TIME    931.91   DAYS  .          *                              
 ******************************************                              
</message>
<message date="20/7/1992" time="931.90720231215448">
 ******************************************                              
 * WELL U1       HAS CHANGED TO           *                              
 * CONTROL BY TUBING HEAD PRESSURE        *                              
 * FROM TIME    931.91   DAYS  .          *                              
 ******************************************                              
</message>
<message date="20/7/1992" time="931.90720231215448">
 **********************************************                          
 * WELL U4       HAS CHANGED TO GROUP CONTROL *                          
 * FROM TIME    931.91   DAYS  .              *                          
 **********************************************                          
</message>
<message date="20/7/1992" time="931.90720231215448">
 **********************************************                          
 * WELL I6       HAS CHANGED TO GROUP CONTROL *                          
 * FROM TIME    931.91   DAYS  .              *                          
 **********************************************                          
</message>
<message date="10/10/1992" time="1013.45360115607730">
 ***********************************************                         
 * DRILLING RIG NUMBER 100 OCCUPIED WITH       *                         
 * WELL I8       UNTIL TIME    1080.00  DAYS   *                         
 ***********************************************                         
</message>
<message date="10/10/1992" time="1013.45360115607730">
 **********************************************************              
 * WELL I8       IS OPENED AT TIME   1013.45  DAYS        *              
 * ( WITH ZERO EFFICIENCY FACTOR UNTIL   1080.00  DAYS  ) *              
 **********************************************************              
</message>
<message date="10/10/1992" time="1013.45360115607730">
 **********************************************                          
 * WELL U2       HAS CHANGED TO GROUP CONTROL *                          
 * FROM TIME   1013.45   DAYS  .              *                          
 **********************************************                          
</message>
<message date="10/10/1992" time="1013.45360115607730">
 ******************************************                              
 * WELL U4       HAS CHANGED TO           *                              
 * CONTROL BY GAS RATE                    *                              
 * FROM TIME   1013.45   DAYS  .          *                              
 ******************************************                              
</message>
<message date="10/10/1992" time="1013.45360115607730">
 **********************************************                          
 * WELL L1       HAS CHANGED TO GROUP CONTROL *                          
 * FROM TIME   1013.45   DAYS  .              *                          
 **********************************************                          
</message>
<message date="10/10/1992" time="1013.45360115607730">
 **********************************************                          
 * WELL I8       HAS CHANGED TO GROUP CONTROL *                          
 * FROM TIME   1013.45   DAYS  .              *                          
 **********************************************                          
</message>
<message date="31/12/1992" time="1095.00000000000000">
 RESTART FILE WRITTEN   REPORT     3                                     
 RESTART INCLUDES FLUIDS IN PLACE                                        
</message>
<message date="31/12/1992" time="1095.00000000000000">
 ******************************************                              
 * WELL L1       HAS CHANGED TO           *                              
 * CONTROL BY OIL RATE                    *                              
 * FROM TIME   1095.00   DAYS  .          *                              
 ******************************************                              
</message>
<message date="18/3/1993" time="1172.14145467295998">
 ******************************************                              
 * WELL U2       HAS CHANGED TO           *                              
 * CONTROL BY TUBING HEAD PRESSURE        *                              
 * FROM TIME   1172.14   DAYS  .          *                              
 ******************************************                              
</message>
<message date="18/3/1993" time="1172.14145467295998">
 **********************************************                          
 * WELL U4       HAS CHANGED TO GROUP CONTROL *                          
 * FROM TIME   1172.14   DAYS  .              *                          
 **********************************************                          
</message>
<message date="17/6/1993" time="1263.15268852231475">
 **********************************************                          
 * WELL LU2      HAS CHANGED TO GROUP CONTROL *                          
 * FROM TIME   1263.15   DAYS  .              *                          
 **********************************************                          
</message>
<message date="17/6/1993" time="1263.15268852231475">
 **********************************************                          
 * WELL U3       HAS CHANGED TO GROUP CONTROL *                          
 * FROM TIME   1263.15   DAYS  .              *                          
 **********************************************                          
</message>
<message date="17/6/1993" time="1263.15268852231475">
 ******************************************                              
 * WELL U4       HAS CHANGED TO           *                              
 * CONTROL BY GAS RATE                    *                              
 * FROM TIME   1263.15   DAYS  .          *                              
 ******************************************                              
</message>
<message date="18/8/1993" time="1325.98160813446270">
 ******************************************                              
 * WELL U3       HAS CHANGED TO           *                              
 * CONTROL BY GAS RATE                    *                              
 * FROM TIME   1325.98   DAYS  .          *                              
 ******************************************                              
</message>
<message date="18/8/1993" time="1325.98160813446270">
 **********************************************                          
 * WELL U4       HAS CHANGED TO GROUP CONTROL *                          
 * FROM TIME   1325.98   DAYS  .              *                          
 **********************************************                          
</message>
<message date="24/10/1993" time="1392.99080406723147">
 ******************************************                              
 * WELL L3       HAS CHANGED TO           *                              
 * CONTROL BY GAS RATE                    *                              
 * FROM TIME   1392.99   DAYS  .          *                              
 ******************************************                              
</message>
<message date="24/10/1993" time="1392.99080406723147">
 ******************************************                              
 * WELL GI       HAS CHANGED TO           *                              
 * CONTROL BY GAS RATE                    *                              
 * FROM TIME   1392.99   DAYS  .          *                              
 ******************************************                              
</message>
<message date="24/10/1993" time="1392.99080406723147">
 **********************************                                      
 * GROUP FIELD    CANNOT MEET ITS *                                      
 *  GAS   INJECTION  TARGET       *                                      
 * AFTER TIME   1392.99   DAYS  . *                                      
 **********************************                                      
</message>
<message date="27/11/1993" time="1426.49540203361585">
 **********************************************                          
 * WELL U3       HAS CHANGED TO GROUP CONTROL *                          
 * FROM TIME   1426.50   DAYS  .              *                          
 **********************************************                          
</message>
<message date="27/11/1993" time="1426.49540203361585">
 ******************************************                              
 * WELL U4       HAS CHANGED TO           *                              
 * CONTROL BY GAS RATE                    *                              
 * FROM TIME   1426.50   DAYS  .          *                              
 ******************************************                              
</message>
<message date="31/12/1993" time="1460.00000000000000">
 RESTART FILE WRITTEN   REPORT     4                                     
 RESTART INCLUDES FLUIDS IN PLACE                                        
</message>
<message date="31/12/1993" time="1460.00000000000000">
 **********************************************************              
 * THE WORST-OFFENDING COMPLETION - NUMBER   1            *              
 * IN WELL U5       AND ALL BELOW IT ARE CLOSED           *              
 * AT TIME    1502.62   DAYS  , BECAUSE                   *              
 * THE FIELD  SALES GAS RATE   5.5208E+04 MSCF/DAY        *              
 * EXCEEDS THE LIMIT   5.5000E+04 MSCF/DAY.               *              
 **********************************************************              
</message>
<message date="31/12/1993" time="1460.00000000000000">
 ****************************************************************        
 * WELL U5       IS  SHUT   AT TIME    1502.62   DAYS   BECAUSE *        
 * IT HAS NO CONNECTIONS OPEN TO THE RESERVOIR.                 *        
 ****************************************************************        
</message>
<message date="11/2/1994" time="1502.62399878791734">
 ******************************************                              
 * WELL U3       HAS CHANGED TO           *                              
 * CONTROL BY GAS RATE                    *                              
 * FROM TIME   1502.62   DAYS  .          *                              
 ******************************************                              
</message>
<message date="11/2/1994" time="1502.62399878791734">
 ******************************************                              
 * WELL L3       HAS CHANGED TO           *                              
 * CONTROL BY TUBING HEAD PRESSURE        *                              
 * FROM TIME   1502.62   DAYS  .          *                              
 ******************************************                              
</message>
<message date="11/2/1994" time="1502.62399878791734">
 **********************************************                          
 * WELL GI       HAS CHANGED TO GROUP CONTROL *                          
 * FROM TIME   1502.62   DAYS  .              *                          
 **********************************************                          
</message>
<message date="11/2/1994" time="1502.62399878791734">
 **********************************                                      
 * GROUP FIELD    CAN MEET ITS    *                                      
 *  GAS   INJECTION  TARGET       *                                      
 * AFTER TIME   1502.62   DAYS  . *                                      
 **********************************                                      
</message>
<message date="25/9/1994" time="1728.88876841326874">
 **********************************************************              
 * THE WORST-OFFENDING CONNECTION - BLOCK ( 13, 10,  7)   *              
 * IN WELL LU2      AND ALL BELOW IT ARE CLOSED           *              
 * AT TIME    1825.00   DAYS  , BECAUSE                   *              
 * THE WELL     WATER CUT      9.5060E-01                 *              
 * EXCEEDS THE LIMIT   9.5000E-01         .               *              
 **********************************************************              
</message>
<message date="25/9/1994" time="1728.88876841326874">
 **********************************************************              
 * THE CONNECTION IN BLOCK ( 13, 10,  2) IN WELL LU2      *              
 * IS OPENED AT TIME    1825.00   DAYS                    *              
 **********************************************************              
</message>
<message date="25/9/1994" time="1728.88876841326874">
 **********************************************************              
 * THE CONNECTION IN BLOCK ( 13, 10,  3) IN WELL LU2      *              
 * IS OPENED AT TIME    1825.00   DAYS                    *              
 **********************************************************              
</message>
<message date="25/9/1994" time="1728.88876841326874">
 **********************************************************              
 * THE CONNECTION IN BLOCK ( 13, 10,  4) IN WELL LU2      *              
 * IS OPENED AT TIME    1825.00   DAYS                    *              
 **********************************************************              
</message>
<message date="25/9/1994" time="1728.88876841326874">
 **********************************************************              
 * THE CONNECTION IN BLOCK ( 13, 10,  5) IN WELL LU2      *              
 * IS OPENED AT TIME    1825.00   DAYS                    *              
 **********************************************************              
</message>
<message date="31/12/1994" time="1825.00000000000000">
 RESTART FILE WRITTEN   REPORT     5                                     
 RESTART INCLUDES FLUIDS IN PLACE                                        
</message>
<message date="31/12/1994" time="1825.00000000000000">
 **********************************************                          
 * WELL LU1      HAS CHANGED TO GROUP CONTROL *                          
 * FROM TIME   1825.00   DAYS  .              *                          
 **********************************************                          
</message>
<message date="31/12/1994" time="1825.00000000000000">
 ******************************************                              
 * WELL LU2      HAS CHANGED TO           *                              
 * CONTROL BY GAS RATE                    *                              
 * FROM TIME   1825.00   DAYS  .          *                              
 ******************************************                              
</message>
<message date="31/12/1994" time="1825.00000000000000">
 ******************************************                              
 * WELL L1       HAS CHANGED TO           *                              
 * CONTROL BY TUBING HEAD PRESSURE        *                              
 * FROM TIME   1825.00   DAYS  .          *                              
 ******************************************                              
</message>
<message date="31/12/1994" time="1825.00000000000000">
 ******************************************                              
 * WELL L2       HAS CHANGED TO           *                              
 * CONTROL BY TUBING HEAD PRESSURE        *                              
 * FROM TIME   1825.00   DAYS  .          *                              
 ******************************************                              
</message>
<message date="31/12/1994" time="1825.00000000000000">
 *********************************************                           
 * WELL U2       IS PUT ON ARTIFICIAL LIFT   *                           
 * AT TIME   1925.57   DAYS  , BECAUSE THE   *                           
 *  OIL   RATE    1.4749E+03  STB/DAY HAS    *                           
 * FALLEN BELOW    2.0000E+03  STB/DAY :     *                           
 * VFP TABLE   2   LIFT QUANTITY  5.0000E-01 *                           
 * WELL EFFICIENCY FACTOR   0.9000           *                           
 *********************************************                           
</message>
<message date="31/12/1994" time="1825.00000000000000">
 **********************************************************              
 * THE WORST-OFFENDING CONNECTION - BLOCK ( 14,  8,  7)   *              
 * IN WELL LU1      AND ALL BELOW IT ARE CLOSED           *              
 * AT TIME    1925.57   DAYS  , BECAUSE                   *              
 * THE WELL     WATER CUT      9.8554E-01                 *              
 * EXCEEDS THE LIMIT   9.5000E-01         .               *              
 **********************************************************              
</message>
<message date="31/12/1994" time="1825.00000000000000">
 **********************************************************              
 * THE CONNECTION IN BLOCK ( 14,  8,  2) IN WELL LU1      *              
 * IS OPENED AT TIME    1925.57   DAYS                    *              
 **********************************************************              
</message>
<message date="31/12/1994" time="1825.00000000000000">
 **********************************************************              
 * THE CONNECTION IN BLOCK ( 14,  8,  3) IN WELL LU1      *              
 * IS OPENED AT TIME    1925.57   DAYS                    *              
 **********************************************************              
</message>
<message date="31/12/1994" time="1825.00000000000000">
 **********************************************************              
 * THE CONNECTION IN BLOCK ( 14,  8,  5) IN WELL LU1      *              
 * IS OPENED AT TIME    1925.57   DAYS                    *              
 **********************************************************              
</message>
<warning date="10/4/1995" time="1925.57153280056627">
 WELL U1       CANNOT PRODUCE AT THE REQUIRED T.H.P.                     
</warning>
<message date="10/4/1995" time="1925.57153280056627">
 WELL U1       CANNOT OPERATE UNDER THE CURRENT                          
 RESERVOIR CONDITIONS IN NON-LINEAR ITERATION   3.                       
 ITS IPR IS    Q(P)  =  A  -  BHP * B ,   WHERE:                         
 A(O,W,G) =   4.4656E+03  3.9866E+04  2.7428E+03                         
 B(O,W,G) =   1.4009E+00  1.2397E+01  8.6043E-01 .                       
 LAST CONVERGED SOLUTION:                                                
     ORAT        WRAT        GRAT        BHP         THP                 
   1.6109E+03  1.2084E+04  2.0458E+03  2.1029E+03  2.0000E+02            
 THE WELL IS STOPPED FOR THE ITERATION.                                  
</message>
<message date="10/4/1995" time="1925.57153280056627">
 ******************************************                              
 * WELL LU1      HAS CHANGED TO           *                              
 * CONTROL BY GAS RATE                    *                              
 * FROM TIME   1925.57   DAYS  .          *                              
 ******************************************                              
</message>
<message date="10/4/1995" time="1925.57153280056627">
 ******************************************                              
 * WELL LU2      HAS CHANGED TO           *                              
 * CONTROL BY TUBING HEAD PRESSURE        *                              
 * FROM TIME   1925.57   DAYS  .          *                              
 ******************************************                              
</message>
<message date="10/4/1995" time="1925.57153280056627">
 *********************************************                           
 * WELL U1       HAS DIED UNDER THP CONTROL  *                           
 * BUT WILL BE REVIVED WITH STRONGER LIFT    *                           
 * AT TIME   1974.23   DAYS  :               *                           
 * VFP TABLE   2   LIFT QUANTITY  5.0000E-01 *                           
 * WELL EFFICIENCY FACTOR    0.900           *                           
 *********************************************                           
</message>
<message date="10/4/1995" time="1925.57153280056627">
 ******************************************                              
 * WELL GI       HAS CHANGED TO           *                              
 * CONTROL BY RESERVOIR FLUID VOLUME RATE *                              
 * FROM TIME   1925.57   DAYS  .          *                              
 ******************************************                              
</message>
<message date="10/4/1995" time="1925.57153280056627">
 **********************************                                      
 * GROUP FIELD    CANNOT MEET ITS *                                      
 *  GAS   INJECTION  TARGET       *                                      
 * AFTER TIME   1925.57   DAYS  . *                                      
 **********************************                                      
</message>
<message date="10/4/1995" time="1925.57153280056627">
 ****************************************************                    
 * THE LIQUID RATE OF WELL U3                       *                    
 * IS REDUCED TO   4.9743E+03  STB/DAY              *                    
 * AT TIME    1974.23   DAYS  , BECAUSE             *                    
 * THE  GAS-OIL RATIO     3.2165E+00 MSCF/STB       *                    
 * EXCEEDS THE CUTBACK LIMIT   3.0000E+00 MSCF/STB. *                    
 ****************************************************                    
</message>
<message date="29/5/1995" time="1974.23020146906788">
 WELL U1       IS REVIVED FOR ITERATION   0                              
</message>
<message date="29/5/1995" time="1974.23020146906788">
 ******************************************                              
 * WELL LU2      HAS CHANGED TO           *                              
 * CONTROL BY OIL RATE                    *                              
 * FROM TIME   1974.23   DAYS  .          *                              
 ******************************************                              
</message>
<message date="29/5/1995" time="1974.23020146906788">
 **********************************************                          
 * WELL U2       HAS CHANGED TO GROUP CONTROL *                          
 * FROM TIME   1974.23   DAYS  .              *                          
 **********************************************                          
</message>
<message date="29/5/1995" time="1974.23020146906788">
 **********************************************                          
 * WELL GI       HAS CHANGED TO GROUP CONTROL *                          
 * FROM TIME   1974.23   DAYS  .              *                          
 **********************************************                          
</message>
<message date="29/5/1995" time="1974.23020146906788">
 **********************************                                      
 * GROUP FIELD    CAN MEET ITS    *                                      
 *  GAS   INJECTION  TARGET       *                                      
 * AFTER TIME   1974.23   DAYS  . *                                      
 **********************************                                      
</message>
<message date="29/5/1995" time="1974.23020146906788">
 ****************************************************                    
 * THE LIQUID RATE OF WELL U3                       *                    
 * IS REDUCED TO   3.9794E+03  STB/DAY              *                    
 * AT TIME    2007.53   DAYS  , BECAUSE             *                    
 * THE  GAS-OIL RATIO     3.2545E+00 MSCF/STB       *                    
 * EXCEEDS THE CUTBACK LIMIT   3.0000E+00 MSCF/STB. *                    
 ****************************************************                    
</message>
<problem date="29/8/1995" time="2066.67836873122724">
 NON-LINEAR EQUATION CONVERGENCE FAILURE                                 
 ITERATION LIMIT REACHED - TIME STEP CHOPPED FROM  61.66                 
</problem>
<warning date="4/9/1995" time="2072.84445038654758">
 LINEAR EQUATIONS NOT FULLY CONVERGED - RUN MAY GO FASTER                
 IF YOU (A) INCREASE NSTACK (= 10 - RUNSPEC SECTION)     16              
     OR (B) MAKE NSTACK NEGATIVE ( EXTENDS STACK ON DISK )               
</warning>
<problem date="4/9/1995" time="2072.84445038654758">
 NON-LINEAR EQUATION CONVERGENCE FAILURE                                 
 ITERATION LIMIT REACHED - TIME STEP CHOPPED FROM   7.71                 
</problem>
<message date="14/9/1995" time="2082.11149656955877">
 ******************************************                              
 * WELL LU2      HAS CHANGED TO           *                              
 * CONTROL BY TUBING HEAD PRESSURE        *                              
 * FROM TIME   2082.11   DAYS  .          *                              
 ******************************************                              
</message>
<message date="14/9/1995" time="2082.11149656955877">
 ******************************************                              
 * WELL U1       HAS CHANGED TO           *                              
 * CONTROL BY BOTTOM HOLE PRESSURE        *                              
 * FROM TIME   2082.11   DAYS  .          *                              
 ******************************************                              
</message>
<message date="19/9/1995" time="2087.85410769765258">
 ******************************************                              
 * WELL U1       HAS CHANGED TO           *                              
 * CONTROL BY TUBING HEAD PRESSURE        *                              
 * FROM TIME   2087.85   DAYS  .          *                              
 ******************************************                              
</message>
<message date="19/9/1995" time="2087.85410769765258">
 *********************************************                           
 * WELL L3       IS PUT ON ARTIFICIAL LIFT   *                           
 * AT TIME   2096.83   DAYS  , BECAUSE THE   *                           
 *  OIL   RATE    1.8193E+03  STB/DAY HAS    *                           
 * FALLEN BELOW    2.0000E+03  STB/DAY :     *                           
 * VFP TABLE   1   LIFT QUANTITY  5.0000E-01 *                           
 * WELL EFFICIENCY FACTOR   0.9000           *                           
 *********************************************                           
</message>
<message date="28/9/1995" time="2096.82693758529922">
 ******************************************                              
 * WELL LU1      HAS CHANGED TO           *                              
 * CONTROL BY TUBING HEAD PRESSURE        *                              
 * FROM TIME   2096.83   DAYS  .          *                              
 ******************************************                              
</message>
<message date="3/11/1995" time="2132.75330725263439">
 **********************************************************              
 * THE WORST-OFFENDING COMPLETION - NUMBER   1            *              
 * IN WELL U1       AND ALL BELOW IT ARE CLOSED           *              
 * AT TIME    2161.38   DAYS  , BECAUSE                   *              
 * THE WELL     WATER CUT      9.5001E-01                 *              
 * EXCEEDS THE LIMIT   9.5000E-01         .               *              
 **********************************************************              
</message>
<message date="3/11/1995" time="2132.75330725263439">
 ****************************************************************        
 * WELL U1       IS  SHUT   AT TIME    2161.38   DAYS   BECAUSE *        
 * IT HAS NO CONNECTIONS OPEN TO THE RESERVOIR.                 *        
 ****************************************************************        
</message>
<message date="2/12/1995" time="2161.37665362631742">
 ******************************************                              
 * WELL U2       HAS CHANGED TO           *                              
 * CONTROL BY TUBING HEAD PRESSURE        *                              
 * FROM TIME   2161.38   DAYS  .          *                              
 ******************************************                              
</message>
<message date="2/12/1995" time="2161.37665362631742">
 ****************************************************                    
 * THE LIQUID RATE OF WELL U2                       *                    
 * IS REDUCED TO   1.4727E+04  STB/DAY              *                    
 * AT TIME    2175.69   DAYS  , BECAUSE             *                    
 * THE  GAS-OIL RATIO     3.5341E+00 MSCF/STB       *                    
 * EXCEEDS THE CUTBACK LIMIT   3.0000E+00 MSCF/STB. *                    
 ****************************************************                    
</message>
<message date="2/12/1995" time="2161.37665362631742">
 **********************************************************              
 * THE WORST-OFFENDING COMPLETION - NUMBER   1            *              
 * IN WELL U2       AND ALL BELOW IT ARE CLOSED           *              
 * AT TIME    2175.69   DAYS  , BECAUSE                   *              
 * THE WELL     WATER CUT      9.5245E-01                 *              
 * EXCEEDS THE LIMIT   9.5000E-01         .               *              
 **********************************************************              
</message>
<message date="2/12/1995" time="2161.37665362631742">
 ****************************************************************        
 * WELL U2       IS  SHUT   AT TIME    2175.69   DAYS   BECAUSE *        
 * IT HAS NO CONNECTIONS OPEN TO THE RESERVOIR.                 *        
 ****************************************************************        
</message>
<message date="31/12/1995" time="2190.00000000000000">
 RESTART FILE WRITTEN   REPORT     6                                     
 RESTART INCLUDES FLUIDS IN PLACE                                        
</message>
<message date="30/12/1996" time="2555.00000000000000">
 RESTART FILE WRITTEN   REPORT     7                                     
 RESTART INCLUDES FLUIDS IN PLACE                                        
</message>
<message date="6/4/1997" time="2652.17625064361209">
 *********************************************                           
 * WELL L2       IS PUT ON ARTIFICIAL LIFT   *                           
 * AT TIME   2764.19   DAYS  , BECAUSE THE   *                           
 *  OIL   RATE    1.8612E+03  STB/DAY HAS    *                           
 * FALLEN BELOW    2.0000E+03  STB/DAY :     *                           
 * VFP TABLE   1   LIFT QUANTITY  5.0000E-01 *                           
 * WELL EFFICIENCY FACTOR   0.9000           *                           
 *********************************************                           
</message>
<message date="27/7/1997" time="2764.19319607215766">
 *********************************************                           
 * WELL L1       IS PUT ON ARTIFICIAL LIFT   *                           
 * AT TIME   2842.10   DAYS  , BECAUSE THE   *                           
 *  OIL   RATE    1.9863E+03  STB/DAY HAS    *                           
 * FALLEN BELOW    2.0000E+03  STB/DAY :     *                           
 * VFP TABLE   1   LIFT QUANTITY  5.0000E-01 *                           
 * WELL EFFICIENCY FACTOR   0.9000           *                           
 *********************************************                           
</message>
<message date="13/10/1997" time="2842.09659803607883">
 **********************************************************              
 * THE WORST-OFFENDING CONNECTION - BLOCK ( 12,  6,  7)   *              
 * IN WELL L3       AND ALL BELOW IT ARE CLOSED           *              
 * AT TIME    2920.00   DAYS  , BECAUSE                   *              
 * THE WELL     WATER CUT      9.5158E-01                 *              
 * EXCEEDS THE LIMIT   9.5000E-01         .               *              
 **********************************************************              
</message>
<message date="13/10/1997" time="2842.09659803607883">
 ****************************************************************        
 * WELL L3       IS  SHUT   AT TIME    2920.00   DAYS   BECAUSE *        
 * IT HAS NO CONNECTIONS OPEN TO THE RESERVOIR.                 *        
 ****************************************************************        
</message>
<message date="30/12/1997" time="2920.00000000000000">
 RESTART FILE WRITTEN   REPORT     8                                     
 RESTART INCLUDES FLUIDS IN PLACE                                        
</message>
<message date="30/12/1997" time="2920.00000000000000">
 ******************************************                              
 * GROUP FIELD    HAS CHANGED TO          *                              
 * WATER  INJECTION  VOIDAGE REPLACEMENT  *                              
 * FROM TIME   2920.00   DAYS  .          *                              
 ******************************************                              
</message>
<message date="19/7/1998" time="3121.28801267604558">
 *********************************************                           
 * WELL LU2      IS PUT ON ARTIFICIAL LIFT   *                           
 * AT TIME   3203.14   DAYS  , BECAUSE THE   *                           
 *  OIL   RATE    1.7067E+03  STB/DAY HAS    *                           
 * FALLEN BELOW    2.0000E+03  STB/DAY :     *                           
 * VFP TABLE   1   LIFT QUANTITY  5.0000E-01 *                           
 * WELL EFFICIENCY FACTOR   0.9000           *                           
 *********************************************                           
</message>
<message date="9/10/1998" time="3203.14400633802279">
 ****************************************************************        
 * WELL LU1      IS STOPPED AT TIME    3285.00   DAYS   BECAUSE *        
 * GROUP ONE      HAS AN OIL RATE   4.4203E+03  STB/DAY         *        
 * BELOW THE MINIMUM ECONOMIC VALUE   5.0000E+03  STB/DAY       *        
 ****************************************************************        
</message>
<message date="9/10/1998" time="3203.14400633802279">
 ****************************************************************        
 * WELL LU2      IS STOPPED AT TIME    3285.00   DAYS   BECAUSE *        
 * GROUP ONE      HAS AN OIL RATE   4.4203E+03  STB/DAY         *        
 * BELOW THE MINIMUM ECONOMIC VALUE   5.0000E+03  STB/DAY       *        
 ****************************************************************        
</message>
<message date="30/12/1998" time="3285.00000000000000">
 RESTART FILE WRITTEN   REPORT     9                                     
 RESTART INCLUDES FLUIDS IN PLACE                                        
</message>
<message date="30/12/1999" time="3650.00000000000000">
 RESTART FILE WRITTEN   REPORT    10                                     
 RESTART INCLUDES FLUIDS IN PLACE                                        
</message>
</eclipse>
