<eclipse>
<message date="1/1/1990" time="0.00000000000000">
 CHECKING FOR LICENSES                                                   
</message>
<message date="1/1/1990" time="0.00000000000000">
 THE MEMORY REQUIRED TO PROCESS THE GRID SECTION IS                      
      41936 BYTES                                                        
</message>
<message date="1/1/1990" time="0.00000000000000">
 UNSPECIFIED TOPS VALUES OBTAINED BY ADDING DZ                           
 TO TOPS VALUE FOR LAYER ABOVE                                           
</message>
<comment date="1/1/1990" time="0.00000000000000">
 NEWTRAN SPECIFIED IN BLOCK-CENTRED GEOMETRY                             
 IS NOT RECOMMENDED. CHECK THE GRID DATA.                                
</comment>
<message date="1/1/1990" time="0.00000000000000">
 4 NON-NEIGHBOUR CONNECTIONS PRESENT                                     
</message>
<comment date="1/1/1990" time="0.00000000000000">
 32 DUAL POROSITY CONNECTIONS FOUND                                      
</comment>
<message date="1/1/1990" time="0.00000000000000">
 NUMBER OF ACTIVE CELLS IS 64                                            
</message>
<message date="1/1/1990" time="0.00000000000000">
 THE MEMORY REQUIRED TO PROCESS THE SOLUTION SECTION IS                  
     492180 BYTES                                                        
</message>
<message date="1/1/1990" time="0.00000000000000">
    58554 CHARACTER VARIABLES USED                                       
</message>
<warning date="1/1/1990" time="0.00000000000000">
  NEGATIVE COMPRESSIBILITY FOUND IN GAS                                  
  PRESSURE TABLE     1 AND OIL PRESSURE                                  
  TABLE     1 AT A SAMPLE PRESSURE VALUE                                 
   4352.43103 . ADJUST SATURATED FLUID                                   
  PROPERTY VALUES AT THIS PRESSURE.                                      
  NEGATIVE COMPRESSIBILITIES OCCUR                                       
  FOR GAS SATURATIONS LESS THAN     0.01048                              
</warning>
<warning date="1/1/1990" time="0.00000000000000">
  NEGATIVE COMPRESSIBILITY FOUND IN GAS                                  
  PRESSURE TABLE     1 AND OIL PRESSURE                                  
  TABLE     1 AT A SAMPLE PRESSURE VALUE                                 
   4662.26897 . ADJUST SATURATED FLUID                                   
  PROPERTY VALUES AT THIS PRESSURE.                                      
  NEGATIVE COMPRESSIBILITIES OCCUR                                       
  FOR GAS SATURATIONS LESS THAN     0.06509                              
</warning>
<warning date="1/1/1990" time="0.00000000000000">
  NEGATIVE COMPRESSIBILITY FOUND IN GAS                                  
  PRESSURE TABLE     1 AND OIL PRESSURE                                  
  TABLE     1 AT A SAMPLE PRESSURE VALUE                                 
   4972.10690 . ADJUST SATURATED FLUID                                   
  PROPERTY VALUES AT THIS PRESSURE.                                      
  NEGATIVE COMPRESSIBILITIES OCCUR                                       
  FOR GAS SATURATIONS LESS THAN     0.11255                              
</warning>
<warning date="1/1/1990" time="0.00000000000000">
 SOCRW+SWCR IS GREATER THAN OR EQUAL TO 1.0                              
 IN CELL (  1,  1,  2)                                                   
  SOCRW=      0.7487 SWCR=      0.2622                                   
</warning>
<warning date="1/1/1990" time="0.00000000000000">
 SOCRW+SWCR IS GREATER THAN OR EQUAL TO 1.0                              
 IN CELL (  2,  1,  2)                                                   
  SOCRW=      0.7487 SWCR=      0.2622                                   
</warning>
<warning date="1/1/1990" time="0.00000000000000">
 SOCRW+SWCR IS GREATER THAN OR EQUAL TO 1.0                              
 IN CELL (  3,  1,  2)                                                   
  SOCRW=      0.7487 SWCR=      0.2622                                   
</warning>
<warning date="1/1/1990" time="0.00000000000000">
 SOCRW+SWCR IS GREATER THAN OR EQUAL TO 1.0                              
 IN CELL (  4,  1,  2)                                                   
  SOCRW=      0.7487 SWCR=      0.2622                                   
</warning>
<warning date="1/1/1990" time="0.00000000000000">
 SOCRW+SWCR IS GREATER THAN OR EQUAL TO 1.0                              
 IN CELL (  1,  2,  2)                                                   
  SOCRW=      0.7487 SWCR=      0.2622                                   
</warning>
<warning date="1/1/1990" time="0.00000000000000">
 SOCRW+SWCR IS GREATER THAN OR EQUAL TO 1.0                              
 IN CELL (  2,  2,  2)                                                   
  SOCRW=      0.7487 SWCR=      0.2622                                   
</warning>
<warning date="1/1/1990" time="0.00000000000000">
 SOCRW+SWCR IS GREATER THAN OR EQUAL TO 1.0                              
 IN CELL (  3,  2,  2)                                                   
  SOCRW=      0.7487 SWCR=      0.2622                                   
</warning>
<warning date="1/1/1990" time="0.00000000000000">
 SOCRW+SWCR IS GREATER THAN OR EQUAL TO 1.0                              
 IN CELL (  4,  2,  2)                                                   
  SOCRW=      0.7487 SWCR=      0.2622                                   
</warning>
<warning date="1/1/1990" time="0.00000000000000">
 SOCRW+SWCR IS GREATER THAN OR EQUAL TO 1.0                              
 IN CELL (  1,  3,  2)                                                   
  SOCRW=      0.7487 SWCR=      0.2622                                   
</warning>
<warning date="1/1/1990" time="0.00000000000000">
 SOCRW+SWCR IS GREATER THAN OR EQUAL TO 1.0                              
 IN CELL (  2,  3,  2)                                                   
  SOCRW=      0.7487 SWCR=      0.2622                                   
</warning>
<warning date="1/1/1990" time="0.00000000000000">
 SOCRW+SWCR IS GREATER THAN OR EQUAL TO 1.0                              
 IN CELL (  3,  3,  2)                                                   
  SOCRW=      0.7487 SWCR=      0.2622                                   
</warning>
<warning date="1/1/1990" time="0.00000000000000">
 SOCRW+SWCR IS GREATER THAN OR EQUAL TO 1.0                              
 IN CELL (  4,  3,  2)                                                   
  SOCRW=      0.7487 SWCR=      0.2622                                   
</warning>
<warning date="1/1/1990" time="0.00000000000000">
 SOCRW+SWCR IS GREATER THAN OR EQUAL TO 1.0                              
 IN CELL (  1,  4,  2)                                                   
  SOCRW=      0.7487 SWCR=      0.2622                                   
</warning>
<warning date="1/1/1990" time="0.00000000000000">
 SOCRW+SWCR IS GREATER THAN OR EQUAL TO 1.0                              
 IN CELL (  2,  4,  2)                                                   
  SOCRW=      0.7487 SWCR=      0.2622                                   
</warning>
<warning date="1/1/1990" time="0.00000000000000">
 SOCRW+SWCR IS GREATER THAN OR EQUAL TO 1.0                              
 IN CELL (  3,  4,  2)                                                   
  SOCRW=      0.7487 SWCR=      0.2622                                   
</warning>
<warning date="1/1/1990" time="0.00000000000000">
 SOCRW+SWCR IS GREATER THAN OR EQUAL TO 1.0                              
 IN CELL (  4,  4,  2)                                                   
  SOCRW=      0.7487 SWCR=      0.2622                                   
</warning>
<warning date="1/1/1990" time="0.00000000000000">
 THE BOTTOM HOLE PRESSURE LIMIT FOR WELL IW                              
 HAS BEEN DEFAULTED. THE DEFAULT VALUE IS  100000.   PSIA                
</warning>
<warning date="1/1/1990" time="0.00000000000000">
 THE BOTTOM HOLE PRESSURE LIMIT FOR WELL IG                              
 HAS BEEN DEFAULTED. THE DEFAULT VALUE IS  100000.   PSIA                
</warning>
<warning date="1/1/1990" time="0.00000000000000">
 THE BOTTOM HOLE PRESSURE LIMIT FOR WELL PX                              
 HAS BEEN DEFAULTED.  THE DEFAULT VALUE IS                               
     14.7   PSIA                                                         
</warning>
<message date="1/1/1990" time="0.10000000000000">
 RESTART FILE WRITTEN   REPORT     1                                     
 RESTART INCLUDES FLUIDS IN PLACE                                        
</message>
<message date="2/1/1990" time="1.00000000000000">
 RESTART FILE WRITTEN   REPORT     2                                     
 RESTART INCLUDES FLUIDS IN PLACE                                        
</message>
<problem date="2/1/1990" time="1.00000000000000">
 NON-LINEAR EQUATION CONVERGENCE FAILURE                                 
 ITERATION LIMIT REACHED - TIME STEP CHOPPED FROM   1.28                 
</problem>
<message date="11/1/1990" time="10.00000000000000">
 RESTART FILE WRITTEN   REPORT     3                                     
 RESTART INCLUDES FLUIDS IN PLACE                                        
</message>
<message date="21/1/1990" time="20.00000000000000">
 RESTART FILE WRITTEN   REPORT     4                                     
 RESTART INCLUDES FLUIDS IN PLACE                                        
</message>
<message date="22/1/1990" time="21.00000000000000">
 RESTART FILE WRITTEN   REPORT     5                                     
 RESTART INCLUDES FLUIDS IN PLACE                                        
</message>
<message date="31/1/1990" time="30.00000000000000">
 RESTART FILE WRITTEN   REPORT     6                                     
 RESTART INCLUDES FLUIDS IN PLACE                                        
</message>
<message date="10/2/1990" time="40.00000000000000">
 RESTART FILE WRITTEN   REPORT     7                                     
 RESTART INCLUDES FLUIDS IN PLACE                                        
</message>
<message date="11/4/1990" time="100.00000000000000">
 RESTART FILE WRITTEN   REPORT     8                                     
 RESTART INCLUDES FLUIDS IN PLACE                                        
</message>
<problem date="2/6/1990" time="152.42883156499386">
 NON-LINEAR EQUATION CONVERGENCE FAILURE                                 
 ITERATION LIMIT REACHED - TIME STEP CHOPPED FROM  20.70                 
</problem>
<message date="20/7/1990" time="200.00000000000000">
 RESTART FILE WRITTEN   REPORT     9                                     
 RESTART INCLUDES FLUIDS IN PLACE                                        
</message>
</eclipse>
