<eclipse>
<message date="1/1/1983" time="0.00000000000000">
 CHECKING FOR LICENSES                                                   
</message>
<message date="1/1/1983" time="0.00000000000000">
 THE MEMORY REQUIRED TO PROCESS THE GRID SECTION IS                      
     640212 BYTES                                                        
</message>
<warning date="1/1/1983" time="0.00000000000000">
   1200 VALUES NOT DEFINED IN BOX (  1- 20,  1- 20,  1-  4)              
 OF KEYWORD TOPS                                                         
</warning>
<message date="1/1/1983" time="0.00000000000000">
 UNSPECIFIED TOPS VALUES OBTAINED BY ADDING DZ                           
 TO TOPS VALUE FOR LAYER ABOVE                                           
</message>
<message date="1/1/1983" time="0.00000000000000">
 NEITHER OLDTRAN,OLDTRANR NOR NEWTRAN SPECIFIED                          
 BLOCK CENTRE TRANSMISSIBILITIES TO BE CALCULATED                        
 USING  OLDTRAN                                                          
</message>
<comment date="1/1/1983" time="0.00000000000000">
 NO NON-NEIGHBOUR CONNECTIONS FOUND                                      
</comment>
<message date="1/1/1983" time="0.00000000000000">
 NUMBER OF ACTIVE CELLS IS 1600                                          
</message>
<message date="1/1/1983" time="0.00000000000000">
 THE MEMORY REQUIRED TO PROCESS THE SOLUTION SECTION IS                  
       1977 KBYTES                                                       
</message>
<message date="1/1/1983" time="0.00000000000000">
    58535 CHARACTER VARIABLES USED                                       
</message>
<warning date="1/1/1983" time="0.00000000000000">
 KEYWORD EHYSTR IS NOT SPECIFIED IN                                      
 RUN WITH HYSTERESIS. CURVATURE PARAMETER IS                             
 DEFAULTED TO    0.10000 AND RELATIVE PERMEABILITY                       
 HYSTERESIS FLAG IS DEFAULTED TO    0                                    
</warning>
<warning date="1/1/1983" time="0.00000000000000">
 THE BOTTOM HOLE PRESSURE LIMIT FOR WELL I                               
 HAS BEEN DEFAULTED. THE DEFAULT VALUE IS  100000.   PSIA                
</warning>
<message date="1/1/1983" time="0.00000000000000">
 RESTART FILE WRITTEN   REPORT     0                                     
</message>
<message date="11/1/1983" time="10.00000000000000">
 RESTART FILE WRITTEN   REPORT     1                                     
</message>
<message date="20/3/1991" time="3000.00000000000000">
 RESTART FILE WRITTEN   REPORT     2                                     
</message>
<warning date="20/3/1991" time="3000.00000000000000">
 THE BOTTOM HOLE PRESSURE LIMIT FOR WELL I                               
 HAS BEEN DEFAULTED. THE DEFAULT VALUE IS  100000.   PSIA                
</warning>
<warning date="20/3/1991" time="3000.00000000000000">
 THE PREFERRED PHASE FOR WELL I        IS RE-SET                         
 TO WATER FLOW, TO MATCH THE INJECTED PHASE.                             
</warning>
<message date="30/3/1991" time="3010.00000000000000">
 RESTART FILE WRITTEN   REPORT     3                                     
</message>
<message date="6/6/1999" time="6000.00000000000000">
 RESTART FILE WRITTEN   REPORT     4                                     
</message>
</eclipse>
