<eclipse>
<message date="1/1/1986" time="0.00000000000000">
 CHECKING FOR LICENSES                                                   
</message>
<message date="1/1/1986" time="0.00000000000000">
 THE MEMORY REQUIRED TO PROCESS THE GRID SECTION IS                      
       2026 KBYTES                                                       
</message>
<message date="1/1/1986" time="0.00000000000000">
 UNSPECIFIED TOPS VALUES OBTAINED BY ADDING DZ                           
 TO TOPS VALUE FOR LAYER ABOVE                                           
</message>
<message date="1/1/1986" time="0.00000000000000">
 NEITHER OLDTRAN,OLDTRANR NOR NEWTRAN SPECIFIED                          
 BLOCK CENTRE TRANSMISSIBILITIES TO BE CALCULATED                        
 USING  OLDTRAN                                                          
</message>
<comment date="1/1/1986" time="0.00000000000000">
 NO NON-NEIGHBOUR CONNECTIONS FOUND                                      
</comment>
<message date="1/1/1986" time="0.00000000000000">
 NUMBER OF ACTIVE CELLS IS 5147                                          
</message>
<message date="1/1/1986" time="0.00000000000000">
 THE MEMORY REQUIRED TO PROCESS THE SOLUTION SECTION IS                  
       7162 KBYTES                                                       
</message>
<message date="1/1/1986" time="0.00000000000000">
    61162 CHARACTER VARIABLES USED                                       
</message>
<message date="1/1/1986" time="0.00000000000000">
 SAVE FILE HAS BEEN WRITTEN.                                             
</message>
<message date="1/1/1986" time="0.00000000000000">
 WUPRICE INITIALISED AS USER DEFINED QUANTITY NO. 1                      
</message>
<message date="1/1/1986" time="0.00000000000000">
 WUPRICE DEFINITION PARSED. UPDATE STATUS SET TO ON.                     
</message>
<message date="1/1/1986" time="0.00000000000000">
 DRSDT KEYWORD HAS NOT BEEN ENTERED, SO THE                              
 MAXIMUM GAS RE-SOLUTION RATE IS DEFAULTED TO INFINITY.                  
</message>
<message date="1/1/1986" time="0.00000000000000">
 RESTART FILE WRITTEN   REPORT     0                                     
</message>
<message date="11/1/1986" time="10.00000000000000">
 RESTART FILE WRITTEN   REPORT     1                                     
</message>
<message date="21/1/1986" time="20.00000000000000">
 RESTART FILE WRITTEN   REPORT     2                                     
</message>
<message date="31/1/1986" time="30.00000000000000">
 RESTART FILE WRITTEN   REPORT     3                                     
</message>
<message date="10/2/1986" time="40.00000000000000">
 RESTART FILE WRITTEN   REPORT     4                                     
</message>
<message date="20/2/1986" time="50.00000000000000">
 RESTART FILE WRITTEN   REPORT     5                                     
</message>
<message date="2/3/1986" time="60.00000000000000">
 RESTART FILE WRITTEN   REPORT     6                                     
</message>
<message date="12/3/1986" time="70.00000000000000">
 RESTART FILE WRITTEN   REPORT     7                                     
</message>
<message date="22/3/1986" time="80.00000000000000">
 RESTART FILE WRITTEN   REPORT     8                                     
</message>
<message date="1/4/1986" time="90.00000000000000">
 RESTART FILE WRITTEN   REPORT     9                                     
</message>
<message date="11/4/1986" time="100.00000000000000">
 RESTART FILE WRITTEN   REPORT    10                                     
</message>
</eclipse>
